import React, { useState, useMemo, useCallback, useRef } from 'react'
import { FileJson, Copy, Download, CheckCircle, AlertCircle, Braces, FileCode, Table } from 'lucide-react'

const COLORS = {
  bg: '#1a1a2e',
  editorBg: '#0d1117',
  outputBg: '#0d1117',
  text: '#e6e6e6',
  textMuted: '#8b949e',
  accent: '#7c6cf0',
  accentHover: '#6a5ce0',
  border: 'rgba(255,255,255,0.08)',
  headerBg: 'rgba(13,17,23,0.9)',
  btnBg: 'rgba(255,255,255,0.06)',
  hoverBg: 'rgba(124,108,240,0.1)',
  success: '#3fb950',
  error: '#f85149',
  warning: '#d29922',
}

const SAMPLE_JSON = `{
  "name": "WebLinuxOS",
  "version": "3.0.0",
  "description": "一个基于 Web 的 Linux 操作系统模拟",
  "active": true,
  "author": {
    "name": "开发者",
    "email": "dev@example.com"
  },
  "features": [
    "文件系统",
    "终端模拟",
    "窗口管理",
    "应用生态"
  ],
  "stats": {
    "users": 25600,
    "downloads": 150000,
    "rating": 4.9
  },
  "config": {
    "theme": "dark",
    "language": "zh-CN",
    "plugins": null
  }
}`

type Tab = 'format' | 'validate' | 'typescript' | 'csv'

function tryParseJSON(text: string): { ok: true; value: unknown } | { ok: false; error: string; line: number; col: number } {
  try {
    return { ok: true, value: JSON.parse(text) }
  } catch (e) {
    const msg = e instanceof Error ? e.message : String(e)
    let line = 1, col = 1
    const posMatch = msg.match(/position\s+(\d+)/i)
    if (posMatch) {
      const pos = parseInt(posMatch[1], 10)
      const before = text.substring(0, pos)
      line = (before.match(/\n/g) || []).length + 1
      const lastNewline = before.lastIndexOf('\n')
      col = pos - lastNewline
    }
    return { ok: false, error: msg, line, col }
  }
}

function jsonToTypeScript(value: unknown, rootName = 'RootObject', indent = 0): string {
  const lines: string[] = []
  const seen = new Map<object, string>()

  function getType(v: unknown, name: string): string {
    if (v === null) return 'null'
    if (v === undefined) return 'void'
    if (typeof v === 'string') return 'string'
    if (typeof v === 'number') return 'number'
    if (typeof v === 'boolean') return 'boolean'
    if (Array.isArray(v)) {
      if (v.length === 0) return 'unknown[]'
      const types = new Set<string>()
      for (const item of v.slice(0, 5)) types.add(getType(item, name + 'Item'))
      const union = [...types]
      return union.length === 1 ? union[0] + '[]' : `(${union.join(' | ')})[]`
    }
    if (typeof v === 'object') {
      const obj = v as Record<string, unknown>
      if (seen.has(obj)) return seen.get(obj)!
      const typeName = name.replace(/[^a-zA-Z0-9]/g, '')
      seen.set(obj, typeName)
      const inner = generateInterface(obj, typeName, indent + 1)
      lines.push(inner)
      return typeName
    }
    return 'unknown'
  }

  function generateInterface(obj: Record<string, unknown>, name: string, ind: number): string {
    const p = '  '.repeat(ind)
    const props: string[] = []
    for (const [key, val] of Object.entries(obj)) {
      const safeKey = /^[a-zA-Z_$][\w$]*$/.test(key) ? key : `"${key}"`
      const type = getType(val, name + capitalize(key))
      props.push(`${p}  ${safeKey}: ${type};`)
    }
    return `${p}interface ${name} {\n${props.join('\n')}\n${p}}`
  }

  function capitalize(s: string): string {
    return s.charAt(0).toUpperCase() + s.slice(1)
  }

  if (typeof value === 'object' && value !== null && !Array.isArray(value)) {
    lines.push(`interface ${rootName} {`)
    const obj = value as Record<string, unknown>
    for (const [key, val] of Object.entries(obj)) {
      const safeKey = /^[a-zA-Z_$][\w$]*$/.test(key) ? key : `"${key}"`
      const type = getType(val, rootName + capitalize(key))
      lines.push(`  ${safeKey}: ${type};`)
    }
    lines.push('}')
    if (lines.length < 200) {
      // sub-interfaces are already generated by getType recursion
    }
  } else if (Array.isArray(value)) {
    if (value.length > 0) {
      const firstType = getType(value[0], rootName + 'Item')
      lines.push(`type ${rootName} = ${firstType};`)
    } else {
      lines.push(`type ${rootName} = unknown[];`)
    }
  }

  return lines.join('\n')
}

function jsonToCSV(value: unknown): string {
  if (!Array.isArray(value)) {
    if (typeof value === 'object' && value !== null) {
      const obj = value as Record<string, unknown>
      const keys = Object.keys(obj)
      const header = keys.map(k => `"${k}"`).join(',')
      const row = keys.map(k => {
        const v = obj[k]
        return `"${String(v ?? '').replace(/"/g, '""')}"`
      }).join(',')
      return header + '\n' + row
    }
    return String(value)
  }
  if (value.length === 0) return ''
  const flatItems = value.map(item => {
    if (typeof item === 'object' && item !== null && !Array.isArray(item)) {
      return item as Record<string, unknown>
    }
    return { value: item }
  })
  const allKeys = new Set<string>()
  for (const item of flatItems) {
    Object.keys(item).forEach(k => allKeys.add(k))
  }
  const keys = [...allKeys]
  const header = keys.map(k => `"${k}"`).join(',')
  const rows = flatItems.map(item => {
    const record = item as Record<string, unknown>
    return keys.map(k => {
      const v = record[k]
      const str = typeof v === 'object' ? JSON.stringify(v) : String(v ?? '')
      return `"${str.replace(/"/g, '""')}"`
    }).join(',')
  })
  return header + '\n' + rows.join('\n')
}

function highlightJSON(text: string): React.ReactNode {
  if (!text) return null
  const lines = text.split('\n')
  let idx = 0
  return lines.map((line, lineIdx) => {
    const nodes: React.ReactNode[] = []
    const regex = /("(?:\\.|[^"\\])*"\s*:)|("(?:\\.|[^"\\])*")|(\b(?:true|false|null)\b)|(-?\d+\.?\d*(?:[eE][+-]?\d+)?)|([{}\[\],])/g
    let lastIndex = 0
    let match: RegExpExecArray | null
    while ((match = regex.exec(line)) !== null) {
      if (match.index > lastIndex) {
        nodes.push(<span key={idx++}>{line.slice(lastIndex, match.index)}</span>)
      }
      const [m, keyPart, stringPart, keywordPart, numberPart, punctPart] = match
      if (keyPart) {
        nodes.push(<span key={idx++} style={{ color: '#f9e2af' }}>{m}</span>)
      } else if (stringPart) {
        nodes.push(<span key={idx++} style={{ color: '#a6e3a1' }}>{m}</span>)
      } else if (keywordPart) {
        nodes.push(<span key={idx++} style={{ color: '#cba6f7' }}>{m}</span>)
      } else if (numberPart) {
        nodes.push(<span key={idx++} style={{ color: '#74c7ec' }}>{m}</span>)
      } else if (punctPart) {
        nodes.push(<span key={idx++} style={{ color: '#6c7086' }}>{m}</span>)
      }
      lastIndex = match.index + m.length
    }
    if (lastIndex < line.length) {
      nodes.push(<span key={idx++}>{line.slice(lastIndex)}</span>)
    }
    return (
      <div key={lineIdx} style={{ minHeight: '1.5em' }}>
        {nodes.length === 0 ? '\u00A0' : nodes}
      </div>
    )
  })
}

export default function JsonFormatter() {
  const [input, setInput] = useState(SAMPLE_JSON)
  const [activeTab, setActiveTab] = useState<Tab>('format')
  const [copyFeedback, setCopyFeedback] = useState('')
  const [splitRatio, setSplitRatio] = useState(0.45)
  const containerRef = useRef<HTMLDivElement>(null)
  const draggingRef = useRef(false)

  const parseResult = useMemo(() => tryParseJSON(input), [input])

  const output = useMemo(() => {
    if (!parseResult.ok) return ''
    try {
      switch (activeTab) {
        case 'format':
          return JSON.stringify(parseResult.value, null, 2)
        case 'validate':
          return JSON.stringify(parseResult.value, null, 2)
        case 'typescript':
          return jsonToTypeScript(parseResult.value)
        case 'csv':
          return jsonToCSV(parseResult.value)
        default:
          return ''
      }
    } catch {
      return '转换错误'
    }
  }, [parseResult, activeTab])

  const lineCount = useMemo(() => output.split('\n').length, [output])
  const inputLineCount = useMemo(() => input.split('\n').length, [input])

  const handleMinify = useCallback(() => {
    if (parseResult.ok) {
      setInput(JSON.stringify(parseResult.value))
    }
  }, [parseResult])

  const handleFormat = useCallback(() => {
    if (parseResult.ok) {
      setInput(JSON.stringify(parseResult.value, null, 2))
    }
  }, [parseResult])

  const handleCopy = useCallback(() => {
    navigator.clipboard.writeText(output).then(() => {
      setCopyFeedback('已复制!')
      setTimeout(() => setCopyFeedback(''), 2000)
    }).catch(() => {
      setCopyFeedback('复制失败')
      setTimeout(() => setCopyFeedback(''), 2000)
    })
  }, [output])

  const handleDownload = useCallback(() => {
    const mimeTypes: Record<Tab, string> = {
      format: 'application/json',
      validate: 'application/json',
      typescript: 'text/typescript',
      csv: 'text/csv',
    }
    const extensions: Record<Tab, string> = {
      format: 'json',
      validate: 'json',
      typescript: 'ts',
      csv: 'csv',
    }
    const blob = new Blob([output], { type: mimeTypes[activeTab] + ';charset=utf-8' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `output.${extensions[activeTab]}`
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
  }, [output, activeTab])

  const handleDragStart = useCallback((e: React.MouseEvent) => {
    e.preventDefault()
    draggingRef.current = true
    const container = containerRef.current
    if (!container) return
    const handleMove = (ev: MouseEvent) => {
      if (!draggingRef.current) return
      const rect = container.getBoundingClientRect()
      setSplitRatio(Math.max(0.2, Math.min(0.8, (ev.clientX - rect.left) / rect.width)))
    }
    const handleUp = () => {
      draggingRef.current = false
      document.removeEventListener('mousemove', handleMove)
      document.removeEventListener('mouseup', handleUp)
      document.body.style.cursor = ''
      document.body.style.userSelect = ''
    }
    document.body.style.cursor = 'col-resize'
    document.body.style.userSelect = 'none'
    document.addEventListener('mousemove', handleMove)
    document.addEventListener('mouseup', handleUp)
  }, [])

  const tabs: { id: Tab; label: string; icon: React.ReactNode }[] = [
    { id: 'format', label: '格式化', icon: <Braces size={13} /> },
    { id: 'validate', label: '验证', icon: <CheckCircle size={13} /> },
    { id: 'typescript', label: 'TS 类型', icon: <FileCode size={13} /> },
    { id: 'csv', label: '转 CSV', icon: <Table size={13} /> },
  ]

  return (
    <div style={{ background: COLORS.bg, height: '100%', display: 'flex', flexDirection: 'column', overflow: 'hidden' }}>
      {/* Header */}
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '8px 12px', background: COLORS.headerBg, borderBottom: `1px solid ${COLORS.border}`, flexShrink: 0 }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
          <FileJson size={16} color={COLORS.accent} />
          <span style={{ color: COLORS.text, fontSize: 14, fontWeight: 600 }}>JSON 格式化工具</span>
          {parseResult.ok ? (
            <span style={{ display: 'flex', alignItems: 'center', gap: 3, color: COLORS.success, fontSize: 11, background: 'rgba(63,185,80,0.1)', padding: '2px 8px', borderRadius: 10 }}>
              <CheckCircle size={11} /> 有效
            </span>
          ) : (
            <span style={{ display: 'flex', alignItems: 'center', gap: 3, color: COLORS.error, fontSize: 11, background: 'rgba(248,81,73,0.1)', padding: '2px 8px', borderRadius: 10 }}>
              <AlertCircle size={11} /> 无效
            </span>
          )}
        </div>
        <div style={{ display: 'flex', alignItems: 'center', gap: 6 }}>
          <button onClick={handleFormat} disabled={!parseResult.ok} style={{ display: 'flex', alignItems: 'center', gap: 4, background: COLORS.btnBg, border: `1px solid ${COLORS.border}`, color: parseResult.ok ? COLORS.textMuted : COLORS.textMuted, padding: '3px 10px', borderRadius: 4, cursor: parseResult.ok ? 'pointer' : 'not-allowed', fontSize: 12, opacity: parseResult.ok ? 1 : 0.5, transition: 'all 0.2s' }}
            onMouseEnter={e => { if (parseResult.ok) { e.currentTarget.style.background = COLORS.hoverBg; e.currentTarget.style.color = COLORS.accent } }}
            onMouseLeave={e => { e.currentTarget.style.background = COLORS.btnBg; e.currentTarget.style.color = COLORS.textMuted }}>
            美化
          </button>
          <button onClick={handleMinify} disabled={!parseResult.ok} style={{ display: 'flex', alignItems: 'center', gap: 4, background: COLORS.btnBg, border: `1px solid ${COLORS.border}`, color: COLORS.textMuted, padding: '3px 10px', borderRadius: 4, cursor: parseResult.ok ? 'pointer' : 'not-allowed', fontSize: 12, opacity: parseResult.ok ? 1 : 0.5, transition: 'all 0.2s' }}
            onMouseEnter={e => { if (parseResult.ok) { e.currentTarget.style.background = COLORS.hoverBg; e.currentTarget.style.color = COLORS.accent } }}
            onMouseLeave={e => { e.currentTarget.style.background = COLORS.btnBg; e.currentTarget.style.color = COLORS.textMuted }}>
            压缩
          </button>
          <div style={{ width: 1, height: 16, background: COLORS.border }} />
          <button onClick={handleCopy} style={{ display: 'flex', alignItems: 'center', gap: 4, background: COLORS.btnBg, border: `1px solid ${COLORS.border}`, color: COLORS.textMuted, padding: '3px 10px', borderRadius: 4, cursor: 'pointer', fontSize: 12, transition: 'all 0.2s' }}
            onMouseEnter={e => { e.currentTarget.style.background = COLORS.hoverBg; e.currentTarget.style.color = COLORS.accent }}
            onMouseLeave={e => { e.currentTarget.style.background = COLORS.btnBg; e.currentTarget.style.color = COLORS.textMuted }}>
            <Copy size={12} />
            {copyFeedback || '复制'}
          </button>
          <button onClick={handleDownload} style={{ display: 'flex', alignItems: 'center', gap: 4, background: COLORS.accent, border: 'none', color: '#fff', padding: '3px 10px', borderRadius: 4, cursor: 'pointer', fontSize: 12, fontWeight: 500, transition: 'background 0.2s' }}
            onMouseEnter={e => { e.currentTarget.style.background = COLORS.accentHover }}
            onMouseLeave={e => { e.currentTarget.style.background = COLORS.accent }}>
            <Download size={12} />
            下载
          </button>
        </div>
      </div>
      {/* Tabs */}
      <div style={{ display: 'flex', gap: 0, padding: '0 12px', background: COLORS.headerBg, borderBottom: `1px solid ${COLORS.border}`, flexShrink: 0 }}>
        {tabs.map(tab => (
          <button key={tab.id} onClick={() => setActiveTab(tab.id)}
            style={{
              display: 'flex', alignItems: 'center', gap: 4, padding: '8px 14px',
              background: 'transparent', border: 'none', borderBottom: activeTab === tab.id ? `2px solid ${COLORS.accent}` : '2px solid transparent',
              color: activeTab === tab.id ? COLORS.accent : COLORS.textMuted,
              cursor: 'pointer', fontSize: 12, fontWeight: 500, transition: 'all 0.2s',
            }}
            onMouseEnter={e => { if (activeTab !== tab.id) e.currentTarget.style.color = COLORS.text }}
            onMouseLeave={e => { if (activeTab !== tab.id) e.currentTarget.style.color = COLORS.textMuted }}>
            {tab.icon}
            {tab.label}
          </button>
        ))}
      </div>
      {/* Main Content */}
      <div ref={containerRef} style={{ flex: 1, display: 'flex', overflow: 'hidden' }}>
        {/* Input */}
        <div style={{ width: `${splitRatio * 100}%`, display: 'flex', flexDirection: 'column', borderRight: `1px solid ${COLORS.border}`, minWidth: 0 }}>
          <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', padding: '6px 12px', background: COLORS.editorBg, borderBottom: `1px solid ${COLORS.border}`, flexShrink: 0 }}>
            <span style={{ color: COLORS.textMuted, fontSize: 11, textTransform: 'uppercase' as const, letterSpacing: 1 }}>输入</span>
            <span style={{ color: COLORS.textMuted, fontSize: 11 }}>{inputLineCount} 行</span>
          </div>
          <div style={{ flex: 1, display: 'flex', overflow: 'hidden', background: COLORS.editorBg }}>
            <div style={{ padding: '12px 0', background: COLORS.editorBg, textAlign: 'right', userSelect: 'none', overflow: 'hidden', flexShrink: 0 }}>
              {Array.from({ length: inputLineCount }, (_, i) => (
                <div key={i} style={{ padding: '0 12px 0 16px', fontSize: 12, lineHeight: '20px', color: '#3b4048', fontFamily: "'SF Mono','Fira Code',monospace" }}>{i + 1}</div>
              ))}
            </div>
            <textarea
              value={input}
              onChange={e => setInput(e.target.value)}
              style={{ flex: 1, background: 'transparent', color: COLORS.text, border: 'none', outline: 'none', resize: 'none', padding: '12px 16px', fontSize: 13, lineHeight: '20px', fontFamily: "'SF Mono','Fira Code',monospace", tabSize: 2, whiteSpace: 'pre', overflow: 'auto' }}
              spellCheck={false}
              placeholder="在此粘贴 JSON 数据..."
            />
          </div>
          {/* Error Bar */}
          {!parseResult.ok && (
            <div style={{ padding: '8px 12px', background: 'rgba(248,81,73,0.08)', borderTop: `1px solid rgba(248,81,73,0.2)`, display: 'flex', alignItems: 'center', gap: 8, flexShrink: 0 }}>
              <AlertCircle size={14} color={COLORS.error} />
              <span style={{ color: COLORS.error, fontSize: 12, flex: 1 }}>
                第 {parseResult.line} 行，第 {parseResult.col} 列: {parseResult.error}
              </span>
            </div>
          )}
        </div>
        {/* Drag Handle */}
        <div
          onMouseDown={handleDragStart}
          style={{ width: 5, cursor: 'col-resize', background: COLORS.border, flexShrink: 0, transition: 'background 0.2s', display: 'flex', alignItems: 'center', justifyContent: 'center' }}
          onMouseEnter={e => { e.currentTarget.style.background = COLORS.accent }}
          onMouseLeave={e => { e.currentTarget.style.background = COLORS.border }}
        >
          <div style={{ width: 2, height: 24, borderRadius: 1, background: COLORS.textMuted, opacity: 0.5 }} />
        </div>
        {/* Output */}
        <div style={{ width: `${(1 - splitRatio) * 100}%`, display: 'flex', flexDirection: 'column', minWidth: 0 }}>
          <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', padding: '6px 12px', background: COLORS.outputBg, borderBottom: `1px solid ${COLORS.border}`, flexShrink: 0 }}>
            <span style={{ color: COLORS.textMuted, fontSize: 11, textTransform: 'uppercase' as const, letterSpacing: 1 }}>
              {activeTab === 'format' ? '格式化输出' : activeTab === 'validate' ? '验证结果' : activeTab === 'typescript' ? 'TypeScript 类型' : 'CSV 输出'}
            </span>
            <span style={{ color: COLORS.textMuted, fontSize: 11 }}>{lineCount} 行</span>
          </div>
          <div style={{ flex: 1, overflow: 'auto', background: COLORS.outputBg, padding: '12px 16px', fontFamily: "'SF Mono','Fira Code',monospace", fontSize: 13, lineHeight: '20px', color: COLORS.text }}>
            {parseResult.ok ? (
              activeTab === 'typescript' || activeTab === 'csv' ? (
                <pre style={{ margin: 0, whiteSpace: 'pre-wrap', wordBreak: 'break-all' }}>{output}</pre>
              ) : (
                <div>{highlightJSON(output)}</div>
              )
            ) : (
              <div style={{ color: COLORS.textMuted, padding: 20, textAlign: 'center' }}>
                <AlertCircle size={32} color={COLORS.error} style={{ marginBottom: 12 }} />
                <div style={{ fontSize: 14, marginBottom: 8 }}>JSON 语法错误</div>
                <div style={{ fontSize: 12, color: COLORS.error }}>请修复输入中的错误后重试</div>
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  )
}
